<?php
$table_billings = new Schema('zzz_22_billings');
$table_billings->add('fee', 'int', 20);
$table_billings->add('month', 'varchar', 256);
$table_billings->add('fine', 'decimal', '20,2');
$table_billings->add('discount', 'decimal', '20,2');
$table_billings->add('scholarship', 'decimal', '20,2');
$table_billings->add('total_fee', 'decimal', '20,2');
$table_billings->add('generated_by_id', 'int', 11);
$table_billings->add('billing_period_id', 'int', 11);
$table_billings->add('student_id', 'int', 11);
$table_billings->add('fiscal_year_id', 'int', 11);
$table_billings->add('print_no', 'int', 11);
$table_billings->add('created_at', 'TIMESTAMP', '', 'null');
$table_billings->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billings->save();

$table_billing_logs = new Schema('zzz_23_billing_logs');
$table_billing_logs->add('billing_period_id', 'int', 11);
$table_billing_logs->add('billing_id', 'int', 11);
$table_billing_logs->add('student_id', 'int', 11);
$table_billing_logs->add('fiscal_year_id', 'int', 11);
$table_billing_logs->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_logs->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_logs->save();

$table_billing_fees = new Schema('zzz_24_billing_fee');
$table_billing_fees->add('class_id', 'int', 11);
$table_billing_fees->add('section_id', 'int', 11);
$table_billing_fees->add('faculty_id', 'int', 11);
$table_billing_fees->add('billing_period_id', 'int', 11);
$table_billing_fees->add('student_type_id', 'int', 11);
$table_billing_fees->add('category_id', 'int', 11);
$table_billing_fees->add('sub_category_id', 'int', 11);
$table_billing_fees->add('fee_id', 'int', 11);
$table_billing_fees->add('student_id', 'int', 11);
$table_billing_fees->add('from_fee', 'decimal', '20,2');
$table_billing_fees->add('to_fee', 'decimal', '20,2');
$table_billing_fees->add('creator_id', 'int', 11);
$table_billing_fees->add('is_saved', 'boolean', '', false);
$table_billing_fees->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_fees->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_fees->save();

$table_billing_fines = new Schema('zzz_25_billing_fine');
$table_billing_fines->add('class_id', 'int', 11);
$table_billing_fines->add('section_id', 'int', 11);
$table_billing_fines->add('faculty_id', 'int', 11);
$table_billing_fines->add('billing_period_id', 'int', 11);
$table_billing_fines->add('student_type_id', 'int', 11);
$table_billing_fines->add('category_id', 'int', 11);
$table_billing_fines->add('sub_category_id', 'int', 11);
$table_billing_fines->add('fine_id', 'int', 11);
$table_billing_fines->add('student_id', 'int', 11);
$table_billing_fines->add('from_fine', 'decimal', '20,2');
$table_billing_fines->add('to_fine', 'decimal', '20,2');
$table_billing_fines->add('creator_id', 'int', 11);
$table_billing_fines->add('is_saved', 'boolean', '', false);
$table_billing_fines->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_fines->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_fines->save();

$table_billing_discounts = new Schema('zzz_26_billing_discount');
$table_billing_discounts->add('class_id', 'int', 11);
$table_billing_discounts->add('section_id', 'int', 11);
$table_billing_discounts->add('faculty_id', 'int', 11);
$table_billing_discounts->add('billing_period_id', 'int', 11);
$table_billing_discounts->add('student_type_id', 'int', 11);
$table_billing_discounts->add('category_id', 'int', 11);
$table_billing_discounts->add('sub_category_id', 'int', 11);
$table_billing_discounts->add('discount_id', 'int', 11);
$table_billing_discounts->add('student_id', 'int', 11);
$table_billing_discounts->add('from_discount', 'decimal', '20,2');
$table_billing_discounts->add('to_discount', 'decimal', '20,2');
$table_billing_discounts->add('creator_id', 'int', 11);
$table_billing_discounts->add('is_saved', 'boolean', '', false);
$table_billing_discounts->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_discounts->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_discounts->save();

$table_billing_scholarships = new Schema('zzz_27_billing_scholarship');
$table_billing_scholarships->add('class_id', 'int', 11);
$table_billing_scholarships->add('section_id', 'int', 11);
$table_billing_scholarships->add('faculty_id', 'int', 11);
$table_billing_scholarships->add('billing_period_id', 'int', 11);
$table_billing_scholarships->add('student_type_id', 'int', 11);
$table_billing_scholarships->add('category_id', 'int', 11);
$table_billing_scholarships->add('sub_category_id', 'int', 11);
$table_billing_scholarships->add('scholarship_id', 'int', 11);
$table_billing_scholarships->add('student_id', 'int', 11);
$table_billing_scholarships->add('from_scholarship', 'decimal', '20,2');
$table_billing_scholarships->add('to_scholarship', 'decimal', '20,2');
$table_billing_scholarships->add('creator_id', 'int', 11);
$table_billing_scholarships->add('is_saved', 'boolean', '', false);
$table_billing_scholarships->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_scholarships->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_scholarships->save();

$table_billing_updates = new Schema('zzz_28_billing_updates');
$table_billing_updates->add('class_id', 'int', 11);
$table_billing_updates->add('section_id', 'int', 11);
$table_billing_updates->add('faculty_id', 'int', 11);
$table_billing_updates->add('billing_period_id', 'int', 11);
$table_billing_updates->add('student_type_id', 'int', 11);
$table_billing_updates->add('category_id', 'int', 11);
$table_billing_updates->add('sub_category_id', 'int', 11);
$table_billing_updates->add('student_id', 'int', 11);
$table_billing_updates->add('from_total_fee', 'decimal', '20,2');
$table_billing_updates->add('to_total_fee', 'decimal', '20,2');
$table_billing_updates->add('creator_id', 'int', 11);
$table_billing_updates->add('is_saved', 'boolean', '', false);
$table_billing_updates->add('created_at', 'TIMESTAMP', '', 'null');
$table_billing_updates->add('updated_at', 'TIMESTAMP', '', 'null');
$table_billing_updates->save();